version: '3.1'

volumes:
  yugiohdb:
    driver: local

services:

  api:
    build:
        context: .
        dockerfile:  docker/api/Dockerfile
    command: "python app.py"
    container_name: api-yugioh
    depends_on:
      - db
    env_file:
      - "docker/api/.env"
    ports:
      - "5000:${PORT:-5000}"
    volumes:
      - ".:/app"

  db:
    container_name: db-yugioh
    build:
        context: .
        dockerfile: docker/db/Dockerfile
    env_file:
      - "docker/db/.env"
    ports:
      - "3307:3306"
    volumes:
      - yugiohdb:/var/lib/mysql